### ISSUE TITLE
User not found

### ISSUE THREAD

**Issue by Urkman** [florianbeer/Instagram-PHP-API#4]
Since a few days ago I always get (for all users) the message "this user does not exist" when I try to access the media of a user like this:

$response = $this->instagram->getUserMedia($instagram_id);

Any idea, why this happens?

**Comment by qbarbosa** [comment]
> Any app created before Nov 17, 2015 will continue to function until June 1, 2016. On that date, the app will automatically be moved to Sandbox Mode if it wasn't approved through the review process.

Source : https://www.instagram.com/developer/
